Creating test database for alias 'default'...
Importing BlpImagePlugin
Importing BmpImagePlugin
Importing BufrStubImagePlugin
Importing CurImagePlugin
Importing DcxImagePlugin
Importing DdsImagePlugin
Importing EpsImagePlugin
Importing FitsImagePlugin
Importing FliImagePlugin
Importing FpxImagePlugin
Image: failed to import FpxImagePlugin: No module named 'olefile'
Importing FtexImagePlugin
Importing GbrImagePlugin
Importing GifImagePlugin
Importing GribStubImagePlugin
Importing Hdf5StubImagePlugin
Importing IcnsImagePlugin
Importing IcoImagePlugin
Importing ImImagePlugin
Importing ImtImagePlugin
Importing IptcImagePlugin
Importing JpegImagePlugin
Importing Jpeg2KImagePlugin
Importing McIdasImagePlugin
Importing MicImagePlugin
Image: failed to import MicImagePlugin: No module named 'olefile'
Importing MpegImagePlugin
Importing MpoImagePlugin
Importing MspImagePlugin
Importing PalmImagePlugin
Importing PcdImagePlugin
Importing PcxImagePlugin
Importing PdfImagePlugin
Importing PixarImagePlugin
Importing PngImagePlugin
Importing PpmImagePlugin
Importing PsdImagePlugin
Importing QoiImagePlugin
Importing SgiImagePlugin
Importing SpiderImagePlugin
Importing SunImagePlugin
Importing TgaImagePlugin
Importing TiffImagePlugin
Importing WebPImagePlugin
Importing WmfImagePlugin
Importing XbmImagePlugin
Importing XpmImagePlugin
Importing XVThumbImagePlugin
Starting new HTTP connection (1): 192.168.178.71:5000
http://192.168.178.71:5000 "POST /ml/process-image HTTP/1.1" 200 72
Starting new HTTP connection (1): 192.168.178.71:5000
http://192.168.178.71:5000 "POST /ml/process HTTP/1.1" 404 207
Not Found: /api/images/1/estimations/
LOG - Upload response: 404 {'error': {'code': '404_NOT_FOUND', 'message': 'Estimation not found.'}}
.Starting new HTTP connection (1): 192.168.178.71:5000
http://192.168.178.71:5000 "POST /ml/process-image HTTP/1.1" 200 72
Not Found: /api/images/2/estimations/
LOG - Upload response: 404 {'error': {'code': '404_NOT_FOUND', 'message': 'Estimation not found.'}}
.Starting new HTTP connection (1): 192.168.178.71:5000
http://192.168.178.71:5000 "POST /ml/process-image HTTP/1.1" 200 72
Bad Request: /api/images/3/ml_result/
Not Found: /api/images/3/estimations/
......Starting new HTTP connection (1): 192.168.178.71:5000
http://192.168.178.71:5000 "POST /ml/process-image HTTP/1.1" 200 72
LOG - Upload response: 201 {'status': 'success', 'data': {'image_id': 4, 'message': 'Image uploaded successfully and queued for processing.'}}
.Starting new HTTP connection (1): 192.168.178.71:5000
http://192.168.178.71:5000 "POST /ml/process-image HTTP/1.1" 200 72
LOG - Upload response: 201 {'status': 'success', 'data': {'image_id': 5, 'message': 'Image uploaded successfully and queued for processing.'}}
Starting new HTTP connection (1): 192.168.178.71:5000
http://192.168.178.71:5000 "POST /ml/process HTTP/1.1" 404 207
FStarting new HTTP connection (1): 192.168.178.71:5000
http://192.168.178.71:5000 "POST /ml/process-image HTTP/1.1" 200 72
Triggering yield estimation for Image 6
.Starting new HTTP connection (1): 192.168.178.71:5000
http://192.168.178.71:5000 "POST /ml/process-image HTTP/1.1" 200 72
Triggering yield estimation for Image 7
LOG - Upload response: 200 {'status': 'success', 'data': {'image_id': 7, 'nb_fruit': 10.0, 'confidence_score': 0.9, 'processed': True}}
.Not Found: /api/images/1/estimations/
FStarting new HTTP connection (1): 192.168.178.71:5000
http://192.168.178.71:5000 "POST /ml/process-image HTTP/1.1" 200 72
LOG - Upload response: 201 {'status': 'success', 'data': {'image_id': 8, 'message': 'Image uploaded successfully and queued for processing.'}}
Triggering yield estimation for Image 8
.Not Found: /api/fields/1/estimations/
FStarting new HTTP connection (1): 192.168.178.71:5000
http://192.168.178.71:5000 "POST /ml/process-image HTTP/1.1" 200 72
.Starting new HTTP connection (1): 192.168.178.71:5000
http://192.168.178.71:5000 "GET /ml/version HTTP/1.1" 200 140
.Starting new HTTP connection (1): 192.168.178.71:5000
http://192.168.178.71:5000 "POST /ml/process-image HTTP/1.1" 200 72
Starting new HTTP connection (1): 192.168.178.71:5000
http://192.168.178.71:5000 "POST /ml/process-image HTTP/1.1" 200 72
.
======================================================================
FAIL: test_007_django_sends_image_to_ml (core.tests.test_workflow.DjangoWorkflowTest)
Test if Django sends image to ML via API, after image upload.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nathalie/coding/PomoloBee/PomoloBeeDjango/core/tests/test_workflow.py", line 139, in test_007_django_sends_image_to_ml
    self.assertEqual(response.status_code, 200)
AssertionError: 404 != 200

======================================================================
FAIL: test_010_fetch_estimations (core.tests.test_workflow.DjangoWorkflowTest)
Test if Django correctly returns yield estimations.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nathalie/coding/PomoloBee/PomoloBeeDjango/core/tests/test_workflow.py", line 211, in test_010_fetch_estimations
    self.assertEqual(response.status_code, 200)
AssertionError: 404 != 200

======================================================================
FAIL: test_013_get_estimations_by_field (core.tests.test_workflow.DjangoWorkflowTest)
GET /fields/{field_id}/estimations/
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nathalie/coding/PomoloBee/PomoloBeeDjango/core/tests/test_workflow.py", line 261, in test_013_get_estimations_by_field
    self.assertEqual(response.status_code, 200)
AssertionError: 404 != 200

----------------------------------------------------------------------
Ran 18 tests in 0.321s

FAILED (failures=3)
Destroying test database for alias 'default'...
